import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img></img>
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>

      <main className={styles.main}>

        {data.map(events => 
        <a key ={events.id}  href = {`/events/${events.id}`}>
          <Image width = {200} height = {100} src = {events.image} alt = {events.title}></Image>
          <h2>{events.title}</h2>
          <p>{events.description}</p>
        </a>)}
      </main>

      <footer className={styles.footer}>
        <p> 2022 Time to Code - A Project</p>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {

  const {events_categories} = await import('/data/data.json')
  console.log(events_categories);

  return {
      props: { 
          data: events_categories,
      },
  };
}